-
  path: /assets/pdf/Praetorius Aeterno gratias Patri.pdf
  title: Aeterno gratias Patri
  composer: Michael Praetorius
  genre: Motet
  voicing: SATTB

-
  path: /assets/pdf/Praetorius Kyrie.pdf
  title: Kyrie
  composer: Michael Praetorius
  genre: Mass Ordinary
  voicing: SATB
-
  path: /assets/pdf/Praetorius Der Morgenstern ist aufgedrungen.pdf
  title: Der Morgenstern ist aufgedrungen
  composer: Michael Praetorius
  genre: Hymn
  voicing: SATB

-
  path: /assets/pdf/Schütz Nunc dimittis SWV 433
  title: Nunc dimittis, SWV 433
  composer: Heinrich Schütz
  genre: Motet
  voicing: SSATTB