# Site settings
title: Liturgical Music
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Build Settings
plugins:
  - jekyll-autoprefixer

# Settings for the autoprefixer plugin
autoprefixer:
  browsers:
    - last 4 versions
    - Safari > 2