# site settings
title: Liturgical Music Repository
plugins:
#  - jekyll-remote-theme

# build settings
plugins:
  - jekyll-autoprefixer

# autoprefixer plugin settings
autoprefixer:
  browsers:
    - last 4 versions
    - Safari > 2